### PR TITLE
Pvpgn integration

### PR DESCRIPTION
**Pull request by Ruk33**
### Will be implemented in another PR
- allow dagger/match-making to be hosted with bot

### Notes
- This PR contains the updates from https://github.com/uakfdotb/ghostpp/pull/40
- example command from pvpgn server: `/pvpgn init`
- example pvpgn name: `PvPGN Realm`
- example command by user `/chost (2)EchoIsles.w3x test`

### Status
- [x] allow any user to create games from the pvpgn integration (`/chost ...`)
- [x] allow the bot to handle multiple games at once
- [x] flood protection
- [x] allow to download maps from urls
- [x] add configuration parameters
- [ ] update MANUAL with usage notes
- [ ] testing
- [x] allow to unhost by whispering main bot instance
- [x] check and print error message if the game fails to be created
- [x] unhost automatically after n minutes of inactivity

### CODE REVIEW

**Comment by kirill-782** [comment]
not bad so planned

**Comment by kirill-782** [comment]
How is this supposed to work?  On pvpgn it is written /chost and then pvpgn redirects the command to one of the bots?

**Comment by Ruk33** [comment]
```
user -> /chost -> pvpgn -> master bot -> slave bot handles request
```

The user talks to PVPGN through the `/chost` command.
PVPGN picks up this command, and talks to the allowed
bot (the one configured by the user) to handle the request.
The bot in charge listens for this request and starts 
spawning slave processes to handle the requests.

**Comment by KuroRaiken** [comment]
I understand that all the updates are over?

**Comment by Ruk33** [comment]
Hello @KuroRaiken not quite yet. It needs more testing and documentation. There seems to be a particular issue where games aren't properly closed.

**Comment by Ruk33** [comment]
Included a few items in the todo list.

**Pull request closed without merging**
